### ISSUE TITLE
Download doesnt work

### ISSUE THREAD

**Issue by ashrafulkhn** [officialpm/Slideshare-Downloader#120]
I am recieving this error alwayas.
`Some server error occured. Please try again later.`

I think this app is not working anymore.

**Comment by officialpm** [comment]
Fixed

**Comment by churongcon** [comment]
Download doesnt work

**Comment by officialpm** [comment]
> Download doesnt work

Try now!

**Comment by wernser412** [comment]
Download doesnt work:
https://es.slideshare.net/logosacademyeduec/area-y-volumen-de-cilindros
