### ISSUE TITLE
The downloaded PDF is very low-resolution

### ISSUE THREAD

**Issue by NightMachinery** [officialpm/Slideshare-Downloader#158]
https://www.slideshare.net/shuntaroy/a-review-of-deep-contextualized-word-representations-peters-2018

A screenshot of the downloaded PDF:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/36224762/212466254-d6cf7e00-72a9-4db0-a460-2517606b1481.png">

Compare with a screenshot of the website:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/36224762/212466297-54e5f24a-1168-49be-90ee-fc72d6255568.png">

**Comment by officialpm** [comment]
Fixed, now high resolution is supported
